### ISSUE TITLE
The example responses doesn't work for status codes that are not equal to 200

### ISSUE THREAD

**Issue by baltika10** [vaclavnovotny/NSwag.Examples#1]
The ProducesResponseType attribute work perfect, but only for results where the status code is 200.
For all other response codes that doesn't work.
I see in the [RequestBodyExampleProcessor] that it filters only for Success status code. (http://github.com/vaclavnovotny/NSwag.Examples/blob/main/src/NSwag.Examples/RequestBodyExampleProcessor.cs#L31)

Is there any specific reason for such limitation? My API can return additional status codes with another structure, and it's looks very reasonable to support any valid status code..

**Comment by vaclavnovotny** [comment]
As I retrospective it, there is no need for such limitation thus it can be removed. 
Just out of curiosity, for which status codes are you returning custom objects? Or do you just want to specify an example for [ProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-5.0)?

**Comment by baltika10** [comment]
Yes, this is the idea, to show how the error will look like.
And it's good idea to be able to set such attribute on Controller level, so it will be shared on all the actions (if the action have attribute with same status code, it will have a priority)

**Comment by vaclavnovotny** [comment]
PR merged.
