### ISSUE TITLE
FromForm and multipart/form-data

### ISSUE THREAD

**Issue by banchmaxedgedenergy** [vaclavnovotny/NSwag.Examples#15]
Hi,

Thank you for really helpful library!

I recently faced with the following issue.  I want to use polymorphic controller with multipart/form-data, so that I have to decorate base model with attribute [FromForm] in my asp.net core web api controller's method... However if I do that then all examples I register with IExampleProvider<T> becomes unavailable, since nswag shows only base class properties and the models (examples) selector disappears. 

Do you know how to solve it?

Thank you!

**Comment by vaclavnovotny** [comment]
Hi @banchmaxedgedenergy,
The way Swagger handles [FromForm] parameters is different from the other parameters. I tried tinkering with it for a while but did not manage to find a way to make it work... Please, feel free to fork and try it, maybe you will be more successful. Let me know!
