### ISSUE TITLE
Reusing SwaggerResponse attribute

### ISSUE THREAD

**Issue by baltika10** [vaclavnovotny/NSwag.Examples#3]
I have a question, 
What was to reason to use [ProducesResponseTypeAttribute]? 
NSwag have very similar attribute [SwaggerResponseAttribute](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/SwaggerResponseAttribute.cs) it also defines a status code and a type, but contains "Description" property as well, which appears in swagger UI as well
I just tried locally to change RequestBodyExampleProcessor to use the SwaggerResponseAttribute and it worked perfectly..
![image](https://user-images.githubusercontent.com/36819543/99300013-bab94500-2854-11eb-8ac1-b791d797827a.png)

**Comment by vaclavnovotny** [comment]
As Rico Suter from NSwag points out [here](https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator), SwaggerResponseAtrribute is deprecated, recommended way is to use ProducesResponseType. 
Use standard code documentation instead (using ///).

**Comment by baltika10** [comment]
I agree, thanks for pointing to my "mistake" :) I think the ticket can be closed then.
