### ISSUE TITLE
Generated examples should use serialiser settings

### ISSUE THREAD

**Issue by davidkeaveny** [vaclavnovotny/NSwag.Examples#4]
I am using camel-casing in my JSON serialiser settings, but when I generate example responses using the `IExampleProvider<T>` interface, the responses are using Pascal-casing. I can't see a setting anywhere in the source code to use the existing (`Newtonsoft`, not `System.Text`) serialiser.

**Comment by vaclavnovotny** [comment]
Hey @davidkeaveny, `NSwag.Examples` does not by itself serialize example objects that you define by implementing `IExampleProvider<T>`, it is solely handled by NSwag. Make sure to set `JsonSerializerSettings` when registering `OpenApiDocument`.
```
services.AddOpenApiDocument(
  (settings, provider) =>
  {
      settings.SerializerSettings = new Newtonsoft.Json.JsonSerializerSettings(...);
      settings.AddExamples(provider);
  });
```

**Comment by davidkeaveny** [comment]
That doesn't appear to be working for me - here's my configuration:
```
services.AddOpenApiDocument((settings, provider) => {
  configure.SerializerSettings = new JsonSerializerSettings
  {
    ContractResolver = new CamelCasePropertyNamesContractResolver(),
    NullValueHandling = NullValueHandling.Ignore,
    DateFormatHandling = DateFormatHandling.IsoDateFormat
  };
  configure.AddExamples(provider);
);
```

and it produces an output like this:
```
{
  "Id": "7582297a-7dbc-4eb0-a6ab-1f3ab7117403",
  "Name": "Front Office",
  "Code": "A-0012",
  "Links": {
    "self": {
      "Href": "https://tempuri.org/cost-centres/7582297a-7dbc-4eb0-a6ab-1f3ab7117403",
      "Description": null
    }
  }
}
```
So no camel casing (e.g. the `Id` property) and no null value ignoring (the `Links.self.Description` property).

By way of contrast, this is the output from the same project for examples which are generated only using the `<example />` XMLDOC comments - both camel casing and null-value ignoring is working. There are no example values for complex types though, which is why I'm giving NSwag.Examples a go.
```
{
  "familyName": "Smith",
  "givenName": "John",
  "dateOfJoining": "2020-11-30",
  "referenceNumber": "A-1232-01",
  "department": {
    "id": "string",
    "name": "string",
    "links": {
      "property1": {
        "href": "https://tempuri.org/resources/057c437c-04f3-40d9-86ad-2b00f69fbf38",
        "description": "The current resource."
      },
      "property2": {
        "href": "https://tempuri.org/resources/057c437c-04f3-40d9-86ad-2b00f69fbf38",
        "description": "The current resource."
      }
    }
  },
  "id": "057c437c-04f3-40d9-86ad-2b00f69fbf38",
  "name": "John SMITH",
  "links": {
    "property1": {
      "href": "https://tempuri.org/resources/057c437c-04f3-40d9-86ad-2b00f69fbf38",
      "description": "The current resource."
    },
    "property2": {
      "href": "https://tempuri.org/resources/057c437c-04f3-40d9-86ad-2b00f69fbf38",
      "description": "The current resource."
    }
  }
}
```

**Comment by vaclavnovotny** [comment]
You are right, NSwag seems to ignore or use different serialization settings when serializing examples. I'll check it on Saturday and hopefully come with a solution.

**Comment by vaclavnovotny** [comment]
Hello @davidkeaveny, sorry it took longer than promised. I just published version `1.0.4` where your issue should be fixed. It seems that NSwag uses the default `SerializerSettings` instead of provided one when serializing example values (https://github.com/RicoSuter/NSwag/issues/2920#issuecomment-700654175). I have fixed it by creating `JObject` directly using configured `SerializerSettings`. Just update the package and make sure `SerializerSettings` are set in `AddOpenApiDocument`

**Comment by davidkeaveny** [comment]
Hello @vaclavnovotny , many thanks for the update. I've updated to v1.0.4 and tried the example generation, the results are good and bad :-)

The good news is that camel-casing is now respected, as are null value exclusions, and the complex types I had before are being populated too. The bad news is that the `JObject` seems to be getting involved in the serialised output - below is the example response for the same endpoint as before - you can see it's now returning an array of objects, each of which has a single property named `value`, which contains the actual data we want:

```
[
  {
    "value": {
      "familyName": "Smith",
      "givenName": "John",
      "dateOfJoining": "2020-11-30T00:00:00",
      "referenceNumber": "A-1232-01",
      "department": {
        "id": "d9e0fa98-ac23-4b5c-9209-e94ab88bfff9",
        "name": "IT",
        "links": {
          "self": {
            "href": "https://tempuri.org/departments/d9e0fa98-ac23-4b5c-9209-e94ab88bfff9/"
          }
        }
      },
      "id": "057c437c-04f3-40d9-86ad-2b00f69fbf38",
      "name": "John Smith",
      "links": {
        "self": {
          "href": "https://tempuri.org/employees/057c437c-04f3-40d9-86ad-2b00f69fbf38/"
        }
      }
    }
  }
]
```
Something similar happens with `[FromBody]` and responses which are `typeof(void)`; with the `[FromBody]` requests, I'm seeing something like this:
```
{
  "value": {
    "familyName": "Smith",
    "givenName": "John",
    "dateOfJoining": "2020-11-30T00:00:00",
    "departmentId": "d9e0fa98-ac23-4b5c-9209-e94ab88bfff9",
    "referenceNumber": "A-1232-01"
  }
}
```
, so it's not adding the outer array as it is for responses, but it's still wrapping with an outer object with the real data on the `value` property. Endpoints which return an empty response (e.g. a DELETE endpoint) and are therefore marked up as returning `typeof(void)` return the following:
```
[
  {}
]
```
, so an array containing a single empty object.

**Comment by vaclavnovotny** [comment]
Hey @davidkeaveny, sorry for the delay, it should be fixed now.

**Comment by davidkeaveny** [comment]
Hi @vaclavnovotny that works perfectly now, many thanks!
