### ISSUE TITLE
Feature request: Ability to specify one or more examples specific to each API endpoint

### ISSUE THREAD

**Issue by icnocop** [vaclavnovotny/NSwag.Examples#8]
Hi.

Thank you for NSwag.Examples.

My API endpoints are explicitly decorated with `[SwaggerRequestExample]` and `[SwaggerResponseExample]` using https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters.

The ability to specify one or more examples specific to each endpoint is the ideal approach to generate the desired results in the OpenAPI spec and swagger UI.

Thank you.

**Comment by vaclavnovotny** [comment]
Hi,
Thanks for the request, I will look into it during the week.

**Comment by icnocop** [comment]
Hi.

I opened PR #9 for your feedback.

Thank you.

**Comment by vaclavnovotny** [comment]
Requested feature added in 1.0.9 release. I have closed the PR #9.
